user = {
    "login": "single_user_a",
    "id": 1,
    "node_id": "MDQ6VXNlcjE=",
    "avatar_url": "https://github.com/images/error/single_user_a_happy.gif",
    "gravatar_id": "",
    "url": "https://api.github.com/users/single_user_a",
    "html_url": "https://github.com/single_user_a",
    "followers_url": "https://api.github.com/users/single_user_a/followers",
    "following_url": "https://api.github.com/users/single_user_a/following{/other_user}",
    "gists_url": "https://api.github.com/users/single_user_a/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/single_user_a/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/single_user_a/subscriptions",
    "organizations_url": "https://api.github.com/users/single_user_a/orgs",
    "repos_url": "https://api.github.com/users/single_user_a/repos",
    "events_url": "https://api.github.com/users/single_user_a/events{/privacy}",
    "received_events_url": "https://api.github.com/users/single_user_a/received_events",
    "type": "User",
    "site_admin": false,
    "name": "monalisa single_user_a",
    "company": "GitHub",
    "blog": "https://github.com/blog",
    "location": "San Francisco",
    "email": "single_user_a@github.com",
    "hireable": false,
    "bio": "There once was...",
    "twitter_username": "monathesingle_user_a",
    "public_repos": 2,
    "public_gists": 1,
    "followers": 20,
    "following": 0,
    "created_at": "2008-01-14T04:33:35Z",
    "updated_at": "2008-01-14T04:33:35Z",
    "private_gists": 81,
    "total_private_repos": 100,
    "owned_private_repos": 100,
    "disk_usage": 10000,
    "collaborators": 8,
    "two_factor_authentication": true,
    "plan": {
      "name": "Medium",
      "space": 400,
      "private_repos": 20,
      "collaborators": 0
    }
  }
  
  module.exports = { user };
  