users = [
    {
      "login": "userA",
      "id": 1,
      "node_id": "MDQ6VXNlcjE=",
      "avatar_url": "https://github.com/images/error/usera_happy.gif",
      "gravatar_id": "",
      "url": "https://api.github.com/users/usera",
      "html_url": "https://github.com/usera",
      "followers_url": "https://api.github.com/users/usera/followers",
      "following_url": "https://api.github.com/users/usera/following{/other_user}",
      "gists_url": "https://api.github.com/users/usera/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/usera/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/usera/subscriptions",
      "organizations_url": "https://api.github.com/users/usera/orgs",
      "repos_url": "https://api.github.com/users/usera/repos",
      "events_url": "https://api.github.com/users/usera/events{/privacy}",
      "received_events_url": "https://api.github.com/users/usera/received_events",
      "type": "User",
      "site_admin": true
    },
    {
        "login": "userB",
        "id": 2,
        "node_id": "ADQ6VCNlcjG=",
        "avatar_url": "https://github.com/images/error/userb_happy.gif",
        "gravatar_id": "",
        "url": "https://api.github.com/users/userb",
        "html_url": "https://github.com/userb",
        "followers_url": "https://api.github.com/users/userb/followers",
        "following_url": "https://api.github.com/users/userb/following{/other_user}",
        "gists_url": "https://api.github.com/users/userb/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/userb/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/userb/subscriptions",
        "organizations_url": "https://api.github.com/users/userb/orgs",
        "repos_url": "https://api.github.com/users/userb/repos",
        "events_url": "https://api.github.com/users/userb/events{/privacy}",
        "received_events_url": "https://api.github.com/users/userb/received_events",
        "type": "User",
        "site_admin": false
      },
      {
        "login": "userC",
        "id": 3,
        "node_id": "ZDQ9VCClcjJ=",
        "avatar_url": "https://github.com/images/error/userc_happy.gif",
        "gravatar_id": "",
        "url": "https://api.github.com/users/userc",
        "html_url": "https://github.com/userc",
        "followers_url": "https://api.github.com/users/userc/followers",
        "following_url": "https://api.github.com/users/userc/following{/other_user}",
        "gists_url": "https://api.github.com/users/userc/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/userc/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/userc/subscriptions",
        "organizations_url": "https://api.github.com/users/userc/orgs",
        "repos_url": "https://api.github.com/users/userc/repos",
        "events_url": "https://api.github.com/users/userc/events{/privacy}",
        "received_events_url": "https://api.github.com/users/userc/received_events",
        "type": "User",
        "site_admin": false
      }
  ]

module.exports = { users };
